### ISSUE TITLE
Local keys storage and Android

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/sdk-java-client#36]
Does storing keys work with Android?
`KeyStorageConfig.INSTANCE.getKeyFolderPath()` is often used with `requireNonNull` which will fail for Android.

`KeyStorage.deleteKeyFolder` has a comment
```
// todo add android support
```

**Comment by veselinovicst** [comment]
The Android part of the application won't be developed yet, this is postponed for the future version, hence this can be closed.
