### ISSUE TITLE
Send messages to other user devices

### ISSUE THREAD

**Issue by filipblnt** [blindnet-io/sdk-java-client#40]
In a multi-device context, when sending a message to another user we need to ensure that:

- A message is sent to all devices of the recipient (A)
- A message is sent to other devices of the sender (B)

Currently (A) works fine but (B) does not. We need to fix this.

For testing:

- Create User1 and User2
- Create another device for User2
- User1 sends a message to User2 -> two messages are sent to User2, one to User2Device1 and one to User2Device2
- User2 reads the message on Device1 and responds to Use1 -> two messages are sent, one to User1 and one to User2Device2
- User2 reads two messages on Device2, one from User1 and from User2Device1

**Comment by noelmace** [comment]
Done from @veselinovicst perspective, but needs to be tested on our side.

**Comment by noelmace** [comment]
@m4rk055 could you please review/test this?
